In [2]:
import numpy as np

# LEET CODE PROBLEMS

### 1929 : CONCATENATION OF ARRAYS

In [29]:
nums = [1,2,1]

#SOLUTION : 1

nums.extend(nums)

ans = nums

ans

#SOLUTION : 2


n=len(nums)
ans = []
for i in range(0,2*n):
    if i<n:
        ans.append(nums[i])
    else:
        ans.append(nums[i-n])



#SOLUTION : 3 

ans = nums*2 


### 1672 : RICHEST CUSTOMER WEALTH

In [37]:
accounts = [[1,2,3],[3,2,1],[3,4,5]]

highest_sum = 0

for i in accounts :
    
    current_sum = sum(i)
    
    if highest_sum < current_sum :
        
        highest_sum = current_sum
    

highest_sum

12

### 1470 : SHUFFLE THE ARRAY

In [49]:
import numpy as np 


nums = np.array([2,5,1,3,4,7])

n = int(len(nums)/2)
j = n
a1 = []
a2 = []
for i in range(n) :
    
    a1.append(nums[i])
    
    a1.append(nums[j])
    
    j = j+1
    
print(a1)


[2, 3, 5, 4, 1, 7]


### MAXIMUM NUMBER OF WORDS FOUND IN A SENTENCE

In [6]:
sentences = ["alice and bob love leetcode", "i think so too", "this is great thanks very much"]

ans = []
for i in sentences :
    
    ans.append(len(i.split()))
    
    
print(max(ans))

6


### 1512 : NUMBER OF GOOD PAIRS IN A LIST

In [3]:
nums = [1,2,3,1,1,3,3]

counter = 0
dict = {}

for i in nums :
    if i in dict :
        counter = counter + dict[i]
        dict[i] = dict[i] + 1
        
    else :
        dict[i] = 1
counter

6

### 771 : JEWELS AND STONES

In [22]:
jewels = 'z'

stones = 'ZZZZ'

jewels = list(jewels)
stones = list(stones)

count = 0

for i in stones :
    
    if i in jewels :
        
        count = count + 1
count


0

In [28]:
jewels = 'aA'
stones = 'aAAbbbb'
count = 0
for i in jewels :
    
    count = count + stones.count(i)
count

3

### 1431 : KIDS WITH GREATEST NUMBER OF CANDIES

In [20]:
candies = [4,2,1,5,6,2]
extraCandies = 2

In [21]:
maxcandies = max(candies)
ans = []


for i in candies :
    if i + extraCandies >= maxcandies :
        
        ans.append('true')
        
    else :
        
        ans.append('false')

ans
    



['true', 'false', 'false', 'true', 'true', 'false']

### 1281 : SUBTRACT THE PRODUCT AND SUM OF DIGITS OF AN INTEGER

In [69]:
n = 4421

n = list(str(n))

In [71]:
total = 0
product = 1


for i in n :
    
    total = total + int(i)



for j in n :
    
    product = product * int(j)
    
product

result = product - total
result

21

In [102]:
nums = [8,1,2,2,3]

sort_nums = sorted(nums)
res = []
        
for i in nums:
    res.append(sort_nums.index(i))

res
    

[4, 0, 1, 1, 3]

In [103]:
sort_nums

[1, 2, 2, 3, 8]

### 1678. GOAL PARSER

In [121]:
command = 'G()()()()(al)'

command.replace('()' , 'o').replace('(al)' , 'al')

command

'G()()()()(al)'

### 1342 : Number of Steps to Reduce a Number to Zero

In [135]:
num = 123

count1 = 0
count2 = 0



while num > 0 :
    
    if num % 2 == 0 :
        
        num = num / 2 
        
        count1 += 1
        
    else : 
        
        num = num - 1
        
        count2 += 1
        
count1 + count2
        


12

### 1528 : Shuffle String

In [176]:
indices = [4,5,6,7,0,2,1,3]

s = "codeleet"

ans = str()

for i in range(len(indices)) : 
    
    ans = ans + s[indices.index(i)]

    
ans

'leetcode'

### 1389 : Create Target Array in the Given Order

In [2]:
nums = [0,1,2,3,4]
index = [0,1,2,2,1]

res = []
for i in range(len(nums)):
    res.insert(index[i], nums[i])
    
res

[0, 4, 1, 3, 2]

### 1859. Sorting the Sentence

In [1]:
s = "is2 sentence4 This1 a3" 

word_list = sorted(s.split(), key = lambda s: s[-1])

' '.join(i[:-1] for i in word_list)

'This is a sentence'

### 1221. Split a String in Balanced Strings

In [2]:
s = "RLRRRLLRLL"

a = 0
b = 0
c = 0

for i in s :
    
    if i == 'R' :
        a += 1
        
    if i == 'L' :
        b += 1
        
    if a == b :
        c += 1
c

2

### FIND IF THE DIGITS OF A NUMBER N EVENLY DIVIDES IT

In [65]:

class Solution:
    def evenlyDivides (self, N):
        ans = 0
        num = N
        while num > 0:
            rem = num % 10
            if rem > 0 and N % rem == 0:
                ans+=1
            num = num//10
        return ans

### REVERSE AN INTEGER

In [64]:
x = -3456
 
result = 0

if x < 0:
    symbol = -1
    x = -x
    
else:
    symbol = 1

while x:
    digits = x % 10
    result = result * 10 + digits
    x //= 10

result*symbol

-6543

### CHECK IF NUMBER IS PALINDROME OR NOT

In [97]:
n = 12121
reverse_n = 0
num = n

while num > 0 :
    digits = num % 10
    reverse_n = reverse_n * 10 + digits
    num = num // 10

reverse_n

if reverse_n == n :
    print('Number is a palindrome')
else :
    print('NOT A PALINDROME')

Number is a palindrome


### GCD AND LCM

In [161]:
a = 8
b = 12
ans = []

for i in range(2,min(a,b)+1):
    if a % i == 0 and b % i == 0 :
        ans.append(i)
        
print('HCF OR GCD :', max(ans))
print('LCM :', (a*b)//max(ans))

HCF OR GCD : 4
LCM : 24


### ARMSTRONG NUMBER

In [162]:
n = 1634
num = n

sum = 0

l = len(str(n))

while num > 0 :
    
    digits = num % 10
    sum = sum + digits ** l
    num = num // 10

if sum == n:
    print('NUMBER IS AN ARMSTRONG NUMBER')
else :
    print('NOT AN ARMSTRONG NUMBER')

NUMBER IS AN ARMSTRONG NUMBER


### PRINT ALL DIVISORS

In [1]:
n = 36

for i in range(1,n+1):
    if n % i == 0:
        print(i)


1
2
3
4
6
9
12
18
36


# RECURSION

In [3]:
def recur(n):
    if n > 0 :
        print('SANCHIT')
        recur(n-1)
        

recur(10)

SANCHIT
SANCHIT
SANCHIT
SANCHIT
SANCHIT
SANCHIT
SANCHIT
SANCHIT
SANCHIT
SANCHIT


In [186]:
def recur2(n):
    if n <= 10:
        print(n)
        recur2(n+1)

recur2(1)

1
2
3
4
5
6
7
8
9
10


In [131]:
def sum_(n):
    if n ==0:
        return n
    return n + sum_(n-1)
    

sum_(6)

21

In [133]:
def factorial(n):
    if n ==0:
        return 
    return n * recur3(n-1)

recur3(4)

24

### REVERSE AN ARRAY

In [15]:
import numpy as np

def swap(arr,l,r):
    if l>=r:
        return 
    else :
        arr[l],arr[r] = arr[r],arr[l] 
        swap(arr,l+1,r-1)
    

A = np.array([1,2,3,4,5,6])

swap(A,0,5)
A

array([6, 5, 4, 3, 2, 1])

### CHECK IF A STRING IS A PALINDROME OR NOT

In [180]:
def pal(i,s):
    if i >= len(s)/2:
        return True
    if s[i] != s[len(s)-i-1]:
        return False
    return pal(i+1,s)

In [184]:
pal(0,'abcddcbe')

False

### FREQUENCY COUNT OF ELEMENTS

In [16]:
a = np.array([10,20,10,40,10])

dict = {}

for i in a:
    if i in dict:
        dict[i] += 1
    else:
        dict[i] = 1
        
for key, value in dict.items():
    if value == 1:
        print(key,':',value)
    
    

20 : 1
40 : 1


### SELECTION SORT

In [6]:
b = np.array([8,0,10,6,3,2])

for i in range(len(b)):
    for j in range(i+1,len(b)):
        
        if b[j] < b[i]:
            
            b[i],b[j] = b[j],b[i]
        print(b)

[ 0  8 10  6  3  2]
[ 0  8 10  6  3  2]
[ 0  8 10  6  3  2]
[ 0  8 10  6  3  2]
[ 0  8 10  6  3  2]
[ 0  8 10  6  3  2]
[ 0  6 10  8  3  2]
[ 0  3 10  8  6  2]
[ 0  2 10  8  6  3]
[ 0  2  8 10  6  3]
[ 0  2  6 10  8  3]
[ 0  2  3 10  8  6]
[ 0  2  3  8 10  6]
[ 0  2  3  6 10  8]
[ 0  2  3  6  8 10]


### BUBBLE SORT

In [28]:
b = np.array([5,4,3,2,1])
print(b)

for i in range(len(b)):
    for j in range(len(b)-i-1):
        if b[j] > b[j+1]:
            b[j],b[j+1] = b[j+1],b[j]
        print(b)

[5 4 3 2 1]
[4 5 3 2 1]
[4 3 5 2 1]
[4 3 2 5 1]
[4 3 2 1 5]
[3 4 2 1 5]
[3 2 4 1 5]
[3 2 1 4 5]
[2 3 1 4 5]
[2 1 3 4 5]
[1 2 3 4 5]


### INSERTION SORT

In [31]:
b = np.array([2,6,5,1,3,4])
print(b)

for i in range(1,len(b)):
    j = i
    while b[j-1] > b[j] and j > 0:
        b[j-1],b[j] = b[j],b[j-1]
        j -= 1
    print(b)

[2 6 5 1 3 4]
[2 6 5 1 3 4]
[2 5 6 1 3 4]
[1 2 5 6 3 4]
[1 2 3 5 6 4]
[1 2 3 4 5 6]


### LARGEST AND SECOND LARGEST ELEMENT IN AN ARRAY

In [3]:
a = np.array([0,0,2,5,1,75,76,78])
max = 0
second_max = 0


for i in range(len(a)):
        if a[i] > max:
            max = a[i]
    

for i in range(len(a)):
    
    if a[i] > second_max and a[i] != max:
        second_max = a[i]
            
print('max', max)
print('second max', second_max)
        
        

max 78
second max 76


### CHECK IF ARRAY IS SORTED OR NOT

In [12]:
a = np.array([1,2,5,3,4])

def sort(n):
    for i in range(len(a)):
        for j in range(i+1,len(a)):
            if (a[j] < a[i]):
                return False
        
    return True

In [13]:
sort(a)

False

### LEFT SHIFT BY ONE

In [76]:
b = [1,2,3,4,5]
n = len(b)
temp = b[0]

for i in range(len(b)-1): 
    b[i] =b[i+1]
    
b[n-1] = temp

b

[2, 3, 4, 5, 1]

### RIGHT SHIFT BY ONE

In [111]:
b = [1,2,3,4,5]

temp = b[4]

for i in range(len(b)-1,0,-1):
    b[i] = b[i-1]
b[0] = temp
b
    

[5, 1, 2, 3, 4]

### PUSH ALL ZEROES TO THE BACK

In [129]:
a = [1,0,2,0,3,4,0,5]

n = len(a)

count = 0

for i in range(n):
    
    if a[i] != 0:
        a[count] = a[i]
        count += 1
        
while count < n :
    a[count] = 0
    count += 1
    
a
        
    

[1, 2, 3, 4, 5, 0, 0, 0]

### PRINT OUT UNIQUE NUMBERS

In [53]:
a = [1,2,3,4]
b = [2,3,4,5]

x = a+b
ans = []
for i in x :
    if i not in ans:
        ans.append(i)
ans


[1, 2, 3, 4, 5]

In [67]:
a = [1,2,3,4,4]

ans = []

for i in a:
    if i not in ans:
        ans.append(i)
ans

[1, 2, 3, 4]

### PRINT ALL POSSIBLE SUBARRAYS

In [130]:
a = [1,2,3,4]

for i in range(len(a)+1):
    for j in range(i):
        print(a[j:i])

[1]
[1, 2]
[2]
[1, 2, 3]
[2, 3]
[3]
[1, 2, 3, 4]
[2, 3, 4]
[3, 4]
[4]


### PRINT ALL POSSIBLE SUBARRAYS OF A GIVEN LENGTH

In [132]:
a = [1,2,3,4,5]
k = 2
n = len(a)
ans = []
for i in range(n-k+1):
    print(a[i:i+k], end = ' ')


[1, 2] [2, 3] [3, 4] [4, 5] 

### PRINT SUM OF ALL SUBARRAYS OF A GIVEN LENGTH

In [133]:
ans = []
for i in range(n - k + 1):
    sum = 0
    for j in range(i, k + i):
        sum += a[j]
    ans.append(sum)
ans
  

[3, 5, 7, 9]

### PRINT MAXIMUM SUM FROM SUBARRAYS OF A GIVEN LENGTH

In [1]:
arr = [1,2,3,4,5]
n = len(arr)
k = 2

window_sum = sum(arr[:k])

  

max_sum = window_sum
  
for i in range(n - k):
    window_sum = window_sum - arr[i] + arr[i + k]
    max_sum = max(window_sum, max_sum)
    
max_sum

9

In [13]:
a = [1,5,3,4]
n = 5

sumtotal = (n*(n+1))/2
sumtotal

sum_a = 0

for i in a:
    sum_a = sum_a + i
sum_a

missing_num = sumtotal - sum_a

missing_num

2.0